---
- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false


##  https://github.com/ansible/ansible-examples/blob/master/lamp_simple/roles/web/tasks/install_httpd.yml